# Generated by Django 4.0.3 on 2022-05-02 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dept_id', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('company', models.CharField(max_length=80)),
                ('ctc', models.PositiveIntegerField()),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.department')),
            ],
            options={
                'db_table': 'emplaoyee',
            },
        ),
    ]
